# Generated by Django 6.0 on 2026-02-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalrequest',
            old_name='total_day',
            new_name='total_days',
        ),
    ]
